import { useEffect, useState } from 'react'
import { ArrowUpRight, Edit3, Search as SearchIcon, SlidersHorizontal, Tag, Trash2, X, Check } from 'lucide-react'
import { deleteMemory, searchMemory, updateMemory } from '../api'
import type { SearchResult } from '../types'
import { PageHeader } from '../components/Layout'

export function Search() {
  const [query, setQuery] = useState(''); const [results, setResults] = useState<SearchResult[]>([]); const [activeTag, setActiveTag] = useState('全部'); const [editingId, setEditingId] = useState<string | null>(null); const [editContent, setEditContent] = useState(''); const [editTags, setEditTags] = useState('')
  useEffect(() => { searchMemory('').then(setResults).catch(() => undefined) }, [])
  const runSearch = async (value = query) => { setQuery(value); setResults(await searchMemory(value)) }
  const beginEdit = (result: SearchResult) => { setEditingId(result.id); setEditContent(result.content); setEditTags(result.tags.join(', ')) }
  const saveEdit = async (id: string) => { const result = await updateMemory(id, editContent.trim(), editTags.split(',').map((tag) => tag.trim()).filter(Boolean)); setResults((prev) => prev.map((item) => item.id === id ? result : item)); setEditingId(null) }
  const remove = async (id: string) => { await deleteMemory(id); setResults((prev) => prev.filter((item) => item.id !== id)) }
  const tags = ['全部', ...Array.from(new Set(results.flatMap((result) => result.tags)))]; const visible = activeTag === '全部' ? results : results.filter((result) => result.tags.includes(activeTag))
  return <div className="page"><PageHeader eyebrow="MEMORY / RETRIEVAL" title="知识检索" description="把过去的观察带回现在的决定。" /><section className="search-shell"><div className="search-bar"><SearchIcon size={20} /><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') runSearch() }} placeholder="搜索记忆、决策、复盘..." /><kbd>Enter</kbd></div><div className="search-tools"><div className="filter-tabs">{tags.map((tag) => <button key={tag} className={activeTag === tag ? 'active' : ''} onClick={() => setActiveTag(tag)}>{tag}</button>)}</div><span className="result-count"><SlidersHorizontal size={14} />{visible.length} 条相关记忆</span></div><div className="results">{visible.map((result) => <article className="result-card" key={result.id}>{editingId === result.id ? <div className="memory-edit"><textarea value={editContent} onChange={(event) => setEditContent(event.target.value)} /><input value={editTags} onChange={(event) => setEditTags(event.target.value)} placeholder="标签，用逗号分隔" /><div><button className="button primary" onClick={() => saveEdit(result.id)}><Check size={14} />保存</button><button className="button ghost" onClick={() => setEditingId(null)}>取消</button></div></div> : <><div className="result-card-top"><span className="result-type"><Tag size={13} /> MEMORY</span><span className="score">匹配度 {Math.round(result.score * 100)}%</span></div><p>{highlight(result.content, query)}</p><div className="result-meta"><div>{result.tags.map((tag) => <span className="tag-chip" key={tag}>{tag}</span>)}</div><span>{result.createdAt}</span><div className="result-actions"><button className="icon-button" onClick={() => beginEdit(result)} aria-label="编辑记忆"><Edit3 size={15} /></button><button className="icon-button danger-icon" onClick={() => remove(result.id)} aria-label="删除记忆"><Trash2 size={15} /></button><button className="icon-button" aria-label="查看详情"><ArrowUpRight size={16} /></button></div></div></>}</article>)}</div>{visible.length === 0 && <div className="empty-state">没有找到相关记忆。试试换一个关键词，或先去灵感速记保存一条。</div>}</section></div>
}

function highlight(content: string, query: string) { if (!query) return content; const parts = content.split(new RegExp(`(${query.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')})`, 'ig')); return parts.map((part, index) => part.toLowerCase() === query.toLowerCase() ? <mark key={index}>{part}</mark> : part) }
